generator:
  class: sfPropelGenerator
  param:
    css: adminGenGemb        
    model_class:           refAssurance
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              refAssurance
    plural:                refAssurances
    route_prefix:          ref_assurance
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
