# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    default_culture:        fr
    # Form security secret (CSRF protection)
    csrf_secret:            f55bf531d3bb833fe4e83d6f47d2db139e28b26b

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    i18n:                   on
    standard_helpers: [Partial, Cache, I18N]
    enabled_modules:
      - auth
      - default
    # index = Authentification
  .actions:
    #page not found
    error_404_module:       errors     # module "errors"
    error_404_action:       error404   # action "executeError404"
    #403 credential required
    secure_module:          errors     # module "errors"
    secure_action:          error403   # action "executeError403"    
    # index = Authentification
    login_module: auth
    login_action: login
