all:
  javascripts:
    - jquery.dataTables.min.js
    - jquery.plugins.js
    - jquery-ui.js
    - jquery.maskedinput-1.3.js 
    - fullcalendar.min.js
    - jquery-ui-timepicker-addon.js
    - i18n/jquery.ui.datepicker-fr.js
  stylesheets: [ dataTable/table_jui.css , ui-lightness/jquery-ui-1.8.17.custom.css , fullcalendar.css  ]