<?php



/**
 * Skeleton subclass for performing query and update operations on the 'lnk_sport_adherent' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:19
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LnkSportAdherentQuery extends BaseLnkSportAdherentQuery {

} // LnkSportAdherentQuery
