<?php

/**
 * Skeleton subclass for performing query and update operations on the 'tbl_adherent' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblAdherentQuery extends BaseTblAdherentQuery {

    public function filterByDatatable($searchs = "") {
        if ($searchs == '')
            return $this;
        $arrayCondition = $arrayCombine = array();
        foreach (explode(" ", $searchs) as $i => $search) {
            $search = '%' . $search . '%';

            $this->condition('NomAdherent' . $i, 'TblAdherent.NomAdherent LIKE ?', $search)
                    ->condition('PrenomAdherent' . $i, 'TblAdherent.PrenomAdherent LIKE ?', $search)
                    ->condition('AdresseAdherent' . $i, 'TblAdherent.AdresseAdherent LIKE ?', $search)
                    ->condition('libelleSport' . $i, 'RefTypeSport.Libelle LIKE ?', $search);

            $arrayCondition[] = 'NomAdherent' . $i;
            $arrayCondition[] = 'PrenomAdherent' . $i;
            $arrayCondition[] = 'AdresseAdherent' . $i;
            $arrayCondition[] = 'libelleSport' . $i;

            $this->combine($arrayCondition, 'or', "combine" . $i);
            $arrayCombine[] = "combine" . $i;
            $arrayCondition = array();
        }

        return $this->combine($arrayCombine, 'and');
    }
    
    public function filterMesAdherentsByDatatable($searchs = "") {
        if ($searchs == '')
            return $this;
        $arrayCondition = $arrayCombine = array();
        foreach (explode(" ", $searchs) as $i => $search) {
            $search = '%' . $search . '%';

            $this->condition('NomAdherent' . $i, 'TblAdherent.NomAdherent LIKE ?', $search)
                    ->condition('PrenomAdherent' . $i, 'TblAdherent.PrenomAdherent LIKE ?', $search);

            $arrayCondition[] = 'NomAdherent' . $i;
            $arrayCondition[] = 'PrenomAdherent' . $i;

            $this->combine($arrayCondition, 'or', "combine" . $i);
            $arrayCombine[] = "combine" . $i;
            $arrayCondition = array();
        }

        return $this->combine($arrayCombine, 'and');
    }

    public function orderByDatatable($col, $order) {
        switch ($col) {
            case 0:
                $this->orderByIdAdherent($order);
                break;
            case 1:
                $this->orderByNomAdherent($order);
                break;
            case 7:
                $this->orderByDateAdhesion($order);
                break;
        }
        return $this;
    }
}

// TblAdherentQuery
