<?php

/**
 * Skeleton subclass for representing a row from the 'tbl_adherent' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblAdherent extends BaseTblAdherent {

    public function __toString() {
        return $this->getNomAdherent() . ' ' . $this->getPrenomAdherent();
    }

    public function toArrayString() {
        $libelleSport = ' -- ';
        $typeAdherent = ' -- ';
        $situationAdherent = ' -- ';
        $niveauAdherent = ' -- ';
        if ($this->getRefTypeSport()) {
            $libelleSport = $this->getRefTypeSport()->getLibelle();
        }
        if ($this->getRefSituation()) {
            $situationAdherent = $this->getRefSituation()->getSituation();
        }
        if ($this->getRefTypeAdherent()) {
            $typeAdherent = $this->getRefTypeAdherent()->getLibelleTypeAdherent();
        }
        if ($this->getRefNiveauAdherent()) {
            $niveauAdherent = $this->getRefNiveauAdherent()->getNiveauAdherentLibelle();
        }

        return array(
            $this->getRefCivilite()->getLibelleCivilite() . ' ' . ucfirst($this->getNomAdherent()) . ',' . ucfirst($this->getPrenomAdherent()),
//            $this->getCinAdherent(),
            $situationAdherent,
            $this->getAgeAdherent(),
            $this->getNumTel(),
//            $this->getAdresseAdherent(),
            $libelleSport,
            $typeAdherent,
            $niveauAdherent,
            $this->getDateAdhesion(),
            "DT_RowId" => "row_" . $this->getIdAdherent()
        );
    }

    public function AdherentstoArrayString() {
        $libelleSport = ' -- ';
        $situationAdherent = ' -- ';
        $niveauAdherent = ' -- ';
        if ($this->getRefTypeSport()) {
            $libelleSport = $this->getRefTypeSport()->getLibelle();
        }
        if ($this->getRefSituation()) {
            $situationAdherent = $this->getRefSituation()->getSituation();
        }
        if ($this->getRefNiveauAdherent()) {
            $niveauAdherent = $this->getRefNiveauAdherent()->getNiveauAdherentLibelle();
        }

        return array(
            $this->getRefCivilite()->getLibelleCivilite() . ' ' . ucfirst($this->getNomAdherent()) . ',' . ucfirst($this->getPrenomAdherent()),
//            $this->getCinAdherent(),
            $situationAdherent,
            $this->getAgeAdherent(),
            $this->getNumTel(),
//            $this->getAdresseAdherent(),
            $libelleSport,
            $niveauAdherent,
            $this->getDateAdhesion(),
            "DT_RowId" => "row_" . $this->getIdAdherent()
        );
    }

    public function PlanningEntrainneurstoArrayString() {
        $joursPlanning = '';
        $horaire = '';
        if ($objJours = $this->getLnkJourEntrainementAdherents()) {
            foreach ($objJours as $objJour) {
                $joursPlanning .= $objJour->getRefJour()->getLibelleJour() . " </br> ";
            }
        }
        if ($this->getSeanceHoraireId()) {
            $horaire .= $this->getRefSeanceHoraire()->getSeanceHoraire() . " </br> ";
        }

        return array(
            $this->getRefCivilite()->getLibelleCivilite() . ' ' . ucfirst($this->getNomAdherent()) . ',' . ucfirst($this->getPrenomAdherent()),
            $this->getRefTypeSport()->getLibelle(),
            $joursPlanning,
            $horaire,
            "DT_RowId" => "row_" . $this->getIdAdherent()
        );
    }

    public function PlanningSportstoArrayString() {
        $joursPlanning = '';
        if ($objJours = $this->getLnkJourEntrainementAdherents()) {
            foreach ($objJours as $objJour) {
                $joursPlanning .= $objJour->getRefJour()->getLibelleJour() . " </br> ";
            }
        }

        return array(
            $this->getRefTypeSport()->getLibelle(),
            $joursPlanning,
            "DT_RowId" => "row_" . $this->getIdAdherent()
        );
    }

}

// TblAdherent
