<?php

/**
 * Skeleton subclass for performing query and update operations on the 'tbl_param_portail' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblParamPortailPeer extends BaseTblParamPortailPeer {

    public static function getByName($name) {
        $criteria = new Criteria();
        $criteria->add(TblParamPortailPeer::PARAM_LIB, $name, Criteria::LIKE);
        $paramPortail = TblParamPortailPeer::doSelectOne($criteria);
        if ($paramPortail == null) {
            $paramPortail = new ParamPortail();
            $paramPortail->setParamLib($name);
            $paramPortail->setParamValue("");
            $paramPortail->save();
        }
        return $paramPortail;
    }

    public static function getValueByName($name) {
        $param = self::getByName($name);
        return $param->getParamValue();
    }

}

// TblParamPortailPeer
