<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tbl_sport' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblSportQuery extends BaseTblSportQuery {

//        public function filterByTypeSport($searchs  = "") {
//        
//        if ($searchs[0] == 3){
//            return $this;
//        }
//        if ($searchs) {
//            return $this->filterByIdTypeSport($searchs[0])->find();
//        }
//        
//    
//    
    public function filterByDatatable($searchs = "") {
        if ($searchs == '')
            return $this;
        $arrayCondition = $arrayCombine = array();
        foreach (explode(" ", $searchs) as $i => $search) {
            $search = '%' . $search . '%';

            $this->condition('IdSport' . $i, 'TblSport.IdSport LIKE ?', $search);

            $arrayCondition[] = 'IdSport' . $i;

            $this->combine($arrayCondition, 'or', "combine" . $i);
            $arrayCombine[] = "combine" . $i;
            $arrayCondition = array();
        }

        return $this->combine($arrayCombine, 'and');
    }

    public function orderByDatatable($col, $order) {
        switch ($col) {
            case 1:
                $this->orderByIdSport($order);
                break;
        }
        return $this;
    }
    
} // TblSportQuery
