<?php

/**
 * Skeleton subclass for representing a row from the 'tbl_sport' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblSport extends BaseTblSport {

    public function toArrayString() {
        $jour = '';
        if ($object = $this->getTblAdherent()->getLnkJourEntrainementAdherents()) {
            foreach ($object as $value) {
                $jour .= $value->getRefJour()->getLibelleJour() . " </br> ";
            }
        }
        return array(
            ucfirst($this->getTblAdherent()->getNomAdherent()) . ' ' . ucfirst($this->getTblAdherent()->getPrenomAdherent()),
            $this->getRefTypeSport()->getLibelle(),
            $jour,
            "DT_RowId" => "row_" . $this->getIdSport()
        );
    }

}

// TblSport
