<?php

/**
 * Skeleton subclass for representing a row from the 'tbl_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6-dev on:
 *
 * 03/27/14 16:29:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TblUser extends BaseTblUser {

    /**
     * Retourn id du profil le plus fort
     * @return unknown_type
     */
    public function getMaxProfil() {
        $arrayProfilId = array();
        $lnkProfils = $this->getLnkUserProfils();
        foreach ($lnkProfils as $lnkProfil) {
            $arrayProfilId[] = $lnkProfil->getProfilId();
        }
        return min($arrayProfilId);
    }

    public function isUserAdmin() {
        return $this->isUserProfilById(1);
    }

}

// TblUser
