propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  lnk_jour_entrainement_adherent:
    _attributes: { phpName: LnkJourEntrainementAdherent, idMethod: native }
    id_jour: { phpName: IdJour, type: INTEGER, primaryKey: true, required: true, foreignTable: ref_jour, foreignReference: id_jour }
    id_adherent: { phpName: IdAdherent, type: INTEGER, primaryKey: true, required: true, foreignTable: tbl_adherent, foreignReference: id_adherent }
    _indexes: { FK_lnk_jour_entrainement_adherent: [id_adherent] }
  lnk_sport_adherent:
    _attributes: { phpName: LnkSportAdherent, idMethod: native }
    id_sport: { phpName: IdSport, type: INTEGER, primaryKey: true, required: true, foreignTable: tbl_sport, foreignReference: id_sport }
    id_adherent: { phpName: IdAdherent, type: INTEGER, primaryKey: true, required: true, foreignTable: tbl_adherent, foreignReference: id_adherent }
    _indexes: { FK_lnk_sport_adherent_: [id_adherent] }
  lnk_user_profil:
    _attributes: { phpName: LnkUserProfil, idMethod: native }
    user_id: { phpName: UserId, type: INTEGER, primaryKey: true, required: true, foreignTable: tbl_user, foreignReference: user_id }
    profil_id: { phpName: ProfilId, type: INTEGER, primaryKey: true, required: true, foreignTable: ref_profil, foreignReference: profil_id }
    _indexes: { FK_lnk_user_profil2: [profil_id] }
  ref_civilite:
    _attributes: { phpName: RefCivilite, idMethod: native }
    id_civilite: { phpName: IdCivilite, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    libelle_civilite: { phpName: LibelleCivilite, type: VARCHAR, size: '255', required: false }
  ref_couleur:
    _attributes: { phpName: RefCouleur, idMethod: native }
    id_couleur: { phpName: IdCouleur, type: INTEGER, primaryKey: true, required: true }
    nom_couleur: { phpName: NomCouleur, type: VARCHAR, size: '100', required: false }
    code: { phpName: Code, type: VARCHAR, size: '100', required: false }
  ref_depenses:
    _attributes: { phpName: RefDepenses, idMethod: native }
    id_ref_depenses: { phpName: IdRefDepenses, type: INTEGER, primaryKey: true, required: true }
    libelle_depenses: { phpName: LibelleDepenses, type: VARCHAR, size: '255', required: false }
  ref_jour:
    _attributes: { phpName: RefJour, idMethod: native }
    id_jour: { phpName: IdJour, type: INTEGER, primaryKey: true, required: true }
    libelle_jour: { phpName: LibelleJour, type: VARCHAR, size: '255', required: false }
  ref_profil:
    _attributes: { phpName: RefProfil, idMethod: native }
    profil_id: { phpName: ProfilId, type: INTEGER, primaryKey: true, required: true }
    profil_libelle: { phpName: ProfilLibelle, type: VARCHAR, size: '200', required: false }
  ref_situation:
    _attributes: { phpName: RefSituation, idMethod: native }
    id_situation: { phpName: IdSituation, type: INTEGER, size: '10', primaryKey: true, required: true }
    situation: { phpName: Situation, type: VARCHAR, size: '255', required: false }
  ref_type_adherent:
    _attributes: { phpName: RefTypeAdherent, idMethod: native }
    id_type_adherent: { phpName: IdTypeAdherent, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    libelle_type_adherent: { phpName: LibelleTypeAdherent, type: VARCHAR, size: '255', required: false }
  ref_type_sport:
    _attributes: { phpName: RefTypeSport, idMethod: native }
    id_type_sport: { phpName: IdTypeSport, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    libelle: { phpName: Libelle, type: VARCHAR, size: '250', required: false }
    montant_sport: { phpName: MontantSport, type: DOUBLE, required: false }
    sport_image_path: { phpName: SportImagePath, type: VARCHAR, size: '255', required: false }
  tbl_adherent:
    _attributes: { phpName: TblAdherent, idMethod: native }
    id_adherent: { phpName: IdAdherent, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    cin_adherent: { phpName: CinAdherent, type: VARCHAR, size: '10', required: false }
    nom_adherent: { phpName: NomAdherent, type: VARCHAR, size: '255', required: false }
    prenom_adherent: { phpName: PrenomAdherent, type: VARCHAR, size: '255', required: false }
    id_civilite: { phpName: IdCivilite, type: INTEGER, required: false, foreignTable: ref_civilite, foreignReference: id_civilite }
    id_situation: { phpName: IdSituation, type: INTEGER, required: false, foreignTable: ref_situation, foreignReference: id_situation }
    age_adherent: { phpName: AgeAdherent, type: INTEGER, required: false }
    num_tel: { phpName: NumTel, type: INTEGER, required: false }
    adresse_adherent: { phpName: AdresseAdherent, type: VARCHAR, size: '255', required: false }
    date_adhesion: { phpName: DateAdhesion, type: TIMESTAMP, required: false }
    id_type_sport: { phpName: IdTypeSport, type: INTEGER, required: false, foreignTable: ref_type_sport, foreignReference: id_type_sport }
    id_type_adherent: { phpName: IdTypeAdherent, type: INTEGER, required: false, foreignTable: ref_type_adherent, foreignReference: id_type_adherent }
    image_adherent: { phpName: ImageAdherent, type: VARCHAR, size: '128', required: false }
    updated_at: { phpName: UpdatedAt, type: TIMESTAMP, required: false }
    deleted_at: { phpName: DeletedAt, type: TIMESTAMP, required: false }
    _indexes: { FK_tbl_client: [id_situation], FK_tbl_adherent_type_fonction: [id_type_adherent], FK_tbl_adherent_ref_type_sport: [id_type_sport], FK_tbl_adherent_civilite: [id_civilite] }
  tbl_depenses:
    _attributes: { phpName: TblDepenses, idMethod: native }
    id_depenses: { phpName: IdDepenses, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    date_depenses: { phpName: DateDepenses, type: DATE, required: false }
    id_ref_depenses: { phpName: IdRefDepenses, type: INTEGER, required: false, foreignTable: ref_depenses, foreignReference: id_ref_depenses }
    montant_depenses: { phpName: MontantDepenses, type: DOUBLE, required: false }
    etat_paiement: { phpName: EtatPaiement, type: BOOLEAN, size: '1', required: false, defaultValue: false }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
    updated_at: { phpName: UpdatedAt, type: TIMESTAMP, required: false }
    deleted_at: { phpName: DeletedAt, type: TIMESTAMP, required: false }
    _indexes: { FK_tbl_depances: [id_ref_depenses] }
    _uniques: { id_depances: [id_depenses] }
  tbl_facture:
    _attributes: { phpName: TblFacture, idMethod: native }
    id_facture: { phpName: IdFacture, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    id_adherent: { phpName: IdAdherent, type: INTEGER, required: false, foreignTable: tbl_adherent, foreignReference: id_adherent }
    prix_facture: { phpName: PrixFacture, type: DOUBLE, required: false }
    date_reglement: { phpName: DateReglement, type: TIMESTAMP, required: false }
    etat_paiement: { phpName: EtatPaiement, type: BOOLEAN, size: '1', required: false, defaultValue: false }
    commentaire: { phpName: Commentaire, type: VARCHAR, size: '255', required: false }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
    deleted_at: { phpName: DeletedAt, type: TIMESTAMP, required: false }
    _indexes: { FK_tbl_facture: [id_adherent] }
  tbl_param_portail:
    _attributes: { phpName: TblParamPortail, idMethod: native }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    param_lib: { phpName: ParamLib, type: VARCHAR, size: '127', required: false }
    param_value: { phpName: ParamValue, type: VARCHAR, size: '255', required: false }
  tbl_sport:
    _attributes: { phpName: TblSport, idMethod: native }
    id_sport: { phpName: IdSport, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    id_type_sport: { phpName: IdTypeSport, type: INTEGER, required: false, foreignTable: ref_type_sport, foreignReference: id_type_sport }
    id_moniteur: { phpName: IdMoniteur, type: INTEGER, required: false, foreignTable: tbl_adherent, foreignReference: id_adherent }
    commentaire: { phpName: Commentaire, type: VARCHAR, size: '255', required: false }
    created_at: { phpName: CreatedAt, type: TIMESTAMP, required: false }
    deleted_at: { phpName: DeletedAt, type: TIMESTAMP, required: false }
    _indexes: { FK_tbl_sport: [id_type_sport], FK_tbl_sporth: [id_moniteur] }
  tbl_user:
    _attributes: { phpName: TblUser, idMethod: native }
    user_id: { phpName: UserId, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    user_nom: { phpName: UserNom, type: VARCHAR, size: '200', required: false }
    user_prenom: { phpName: UserPrenom, type: VARCHAR, size: '200', required: false }
    user_login: { phpName: UserLogin, type: VARCHAR, size: '200', required: false }
    user_password: { phpName: UserPassword, type: VARCHAR, size: '200', required: false }
    user_mail: { phpName: UserMail, type: VARCHAR, size: '200', required: false }
    user_compte_active: { phpName: UserCompteActive, type: BOOLEAN, size: '1', required: false }
    user_last_cnx: { phpName: UserLastCnx, type: TIMESTAMP, required: false }
    user_nb_cnx: { phpName: UserNbCnx, type: INTEGER, required: false }
