generator:
  class: sfPropelGenerator
  param:
    css: adminGenGemb
    model_class:           RefTypeSport
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              RefTypeSport
    plural:                RefTypeSports
    route_prefix:          ref_type_sport
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
